#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# LIDCO Installer — Linux / macOS
# ─────────────────────────────────────────────────────────────────────────────
#
# Usage:
#   chmod +x install.sh
#   ./install.sh
#
# What it does:
#   1. Creates Python virtual environment
#   2. Installs all dependencies
#   3. Copies .env.example → .env (if not exists)
#   4. Creates global 'lidco' command in ~/.local/bin
#   5. Ready to use from any directory
# ─────────────────────────────────────────────────────────────────────────────

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

LIDCO_DIR="$(cd "$(dirname "$0")" && pwd)"
VENV_DIR="$LIDCO_DIR/.venv"
BIN_DIR="$HOME/.local/bin"

info()    { echo -e "${CYAN}[INFO]${NC} $1"; }
success() { echo -e "${GREEN}[OK]${NC} $1"; }
warn()    { echo -e "${YELLOW}[WARN]${NC} $1"; }
error()   { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }

echo -e "${BOLD}"
echo "  LIDCO Installer"
echo "  LLM-Integrated Development COmpanion"
echo -e "${NC}"
echo "  Project: $LIDCO_DIR"
echo ""

# ── Check Python ──────────────────────────────────────────────────────────────

PYTHON=""
for cmd in python3 python; do
    if command -v "$cmd" &>/dev/null; then
        version=$("$cmd" --version 2>&1 | grep -oP '\d+\.\d+')
        major=$(echo "$version" | cut -d. -f1)
        minor=$(echo "$version" | cut -d. -f2)
        if [ "$major" -ge 3 ] && [ "$minor" -ge 12 ]; then
            PYTHON="$cmd"
            break
        fi
    fi
done

if [ -z "$PYTHON" ]; then
    error "Python 3.12+ is required. Install from https://python.org"
fi

success "Python found: $($PYTHON --version)"

# ── Create venv ───────────────────────────────────────────────────────────────

if [ -d "$VENV_DIR" ]; then
    info "Virtual environment already exists: $VENV_DIR"
else
    info "Creating virtual environment..."
    "$PYTHON" -m venv "$VENV_DIR"
    success "Virtual environment created"
fi

# Activate
source "$VENV_DIR/bin/activate"
success "Virtual environment activated"

# ── Install dependencies ──────────────────────────────────────────────────────

info "Installing dependencies (this may take a minute)..."
pip install --upgrade pip -q
pip install -e ".[dev]" -q
success "Dependencies installed"

# ── Setup .env ────────────────────────────────────────────────────────────────

if [ ! -f "$LIDCO_DIR/.env" ]; then
    cp "$LIDCO_DIR/.env.example" "$LIDCO_DIR/.env"
    warn ".env created from .env.example — add your API keys there"
else
    info ".env already exists, skipping"
fi

# ── Create global launcher ────────────────────────────────────────────────────

mkdir -p "$BIN_DIR"

cat > "$BIN_DIR/lidco" << LAUNCHER
#!/usr/bin/env bash
# LIDCO launcher — auto-generated by install.sh
export PYTHONIOENCODING=utf-8

if [ -z "\$VIRTUAL_ENV" ]; then
    source "$VENV_DIR/bin/activate"
fi

python -m lidco "\$@"
LAUNCHER

chmod +x "$BIN_DIR/lidco"

cat > "$BIN_DIR/lidco-serve" << LAUNCHER
#!/usr/bin/env bash
# LIDCO server launcher — auto-generated by install.sh
export PYTHONIOENCODING=utf-8

if [ -z "\$VIRTUAL_ENV" ]; then
    source "$VENV_DIR/bin/activate"
fi

python -m lidco serve "\$@"
LAUNCHER

chmod +x "$BIN_DIR/lidco-serve"

success "Launcher created: $BIN_DIR/lidco"

# ── Check PATH ────────────────────────────────────────────────────────────────

if echo "$PATH" | tr ':' '\n' | grep -q "$BIN_DIR"; then
    success "$BIN_DIR is in PATH"
else
    warn "$BIN_DIR is not in PATH. Add it:"
    echo ""
    echo "  # Add to ~/.bashrc or ~/.zshrc:"
    echo "  export PATH=\"\$HOME/.local/bin:\$PATH\""
    echo ""
fi

# ── Done ──────────────────────────────────────────────────────────────────────

echo ""
echo -e "${GREEN}${BOLD}  Installation complete!${NC}"
echo ""
echo "  Usage:"
echo "    lidco              — interactive CLI"
echo "    lidco serve        — HTTP server (port 8321)"
echo "    lidco-serve        — shortcut for server"
echo ""
echo "  First time? Edit .env and add your API key:"
echo "    nano $LIDCO_DIR/.env"
echo ""
