# src/lidco/scaffold/test_gen.py
"""AI-powered test generator — produces pytest test stubs for Python modules."""

from __future__ import annotations

import ast
import textwrap
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any


@dataclass
class FunctionSignature:
    name: str
    args: list[str]
    is_async: bool
    docstring: str


@dataclass
class GeneratedTests:
    source_path: str
    test_code: str
    functions_covered: list[str] = field(default_factory=list)
    error: str = ""


def _extract_functions(source: str) -> list[FunctionSignature]:
    """Parse Python source and extract top-level function/method signatures."""
    try:
        tree = ast.parse(source)
    except SyntaxError:
        return []

    sigs: list[FunctionSignature] = []
    for node in ast.walk(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            if node.name.startswith("_"):
                continue
            args = [a.arg for a in node.args.args if a.arg != "self"]
            doc = ast.get_docstring(node) or ""
            sigs.append(FunctionSignature(
                name=node.name,
                args=args,
                is_async=isinstance(node, ast.AsyncFunctionDef),
                docstring=doc,
            ))
    return sigs


class TestGenerator:
    """Generate pytest test stubs for Python source files.

    When an LLM client is provided, uses it to generate richer tests.
    Without a client, generates structural stubs based on AST parsing.
    """

    def __init__(self, llm_client: Any = None) -> None:
        self._llm = llm_client

    def _stub_for(self, func: FunctionSignature, module_name: str) -> str:
        """Generate a minimal test stub for one function."""
        indent = "    "
        prefix = "async " if func.is_async else ""
        call_prefix = "await " if func.is_async else ""
        arg_list = ", ".join(f"None" for _ in func.args) if func.args else ""
        lines = [
            f"{prefix}def test_{func.name}():",
            f'{indent}"""Test {func.name}."""',
            f"{indent}from {module_name} import {func.name}",
            f"{indent}result = {call_prefix}{func.name}({arg_list})",
            f"{indent}assert result is not None  # TODO: add real assertion",
        ]
        return "\n".join(lines)

    def generate_for_module(self, source_path: str) -> GeneratedTests:
        """Generate test stubs for all public functions in source_path."""
        p = Path(source_path)
        if not p.exists():
            return GeneratedTests(source_path=source_path, test_code="", error=f"File not found: {source_path}")

        try:
            source = p.read_text(encoding="utf-8", errors="replace")
        except OSError as e:
            return GeneratedTests(source_path=source_path, test_code="", error=str(e))

        funcs = _extract_functions(source)
        if not funcs:
            return GeneratedTests(
                source_path=source_path,
                test_code=f'"""No public functions found in {p.name}."""\n',
                functions_covered=[],
            )

        # Derive module name from path
        module_name = p.stem

        header = f'"""Auto-generated tests for {p.name}.\n\nGenerated by LIDCO TestGenerator.\n"""\nimport pytest\n\n'
        stubs = "\n\n".join(self._stub_for(f, module_name) for f in funcs)
        test_code = header + stubs + "\n"

        return GeneratedTests(
            source_path=source_path,
            test_code=test_code,
            functions_covered=[f.name for f in funcs],
        )

    def write_test_file(self, test_code: str, output_path: str) -> str:
        """Write test_code to output_path, creating parent dirs as needed."""
        p = Path(output_path)
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(test_code, encoding="utf-8")
        return str(p)

    async def generate_async(self, source_path: str, function_name: str | None = None) -> GeneratedTests:
        """Generate tests, optionally using LLM for richer stubs.

        Falls back to AST-based generation if LLM is unavailable.
        """
        if self._llm is None:
            return self.generate_for_module(source_path)

        p = Path(source_path)
        if not p.exists():
            return GeneratedTests(source_path=source_path, test_code="", error=f"File not found: {source_path}")

        source = p.read_text(encoding="utf-8", errors="replace")
        funcs = _extract_functions(source)
        if function_name:
            funcs = [f for f in funcs if f.name == function_name]

        if not funcs:
            return self.generate_for_module(source_path)

        prompt = (
            f"Generate pytest tests for the following Python functions from {p.name}:\n"
            + "\n".join(f"- {f.name}({', '.join(f.args)})" for f in funcs)
            + f"\n\nSource:\n```python\n{source[:3000]}\n```\n"
            + "Return only the test code, no explanation."
        )
        try:
            response = await self._llm.complete(prompt)
            test_code = response if isinstance(response, str) else str(response)
        except Exception:
            return self.generate_for_module(source_path)

        return GeneratedTests(
            source_path=source_path,
            test_code=test_code,
            functions_covered=[f.name for f in funcs],
        )
