"""Project setup wizard for LIDCO — Task 435.

Interactive step-by-step setup using prompt_toolkit prompts.
"""

from __future__ import annotations

import os
from dataclasses import dataclass
from pathlib import Path
from typing import Any


# ---------------------------------------------------------------------------
# Data classes
# ---------------------------------------------------------------------------

@dataclass
class WizardResult:
    """Result produced by the setup wizard.

    Attributes:
        project_type: Detected or selected project type (python/js/go/rust/etc).
        agent: Primary agent name selected during setup.
        model: LLM model preference.
        api_key_set: Whether the user set an API key during setup.
    """

    project_type: str
    agent: str
    model: str
    api_key_set: bool


# ---------------------------------------------------------------------------
# Project type detection
# ---------------------------------------------------------------------------

def detect_project_type(path: str | Path = ".") -> str:
    """Detect the primary project type by checking for well-known files.

    Returns one of: ``python``, ``javascript``, ``go``, ``rust``, ``unknown``.
    """
    root = Path(path)

    markers: list[tuple[str, str]] = [
        ("pyproject.toml", "python"),
        ("setup.py", "python"),
        ("setup.cfg", "python"),
        ("requirements.txt", "python"),
        ("package.json", "javascript"),
        ("go.mod", "go"),
        ("Cargo.toml", "rust"),
    ]

    for filename, project_type in markers:
        if (root / filename).exists():
            return project_type

    return "unknown"


# ---------------------------------------------------------------------------
# Wizard implementation
# ---------------------------------------------------------------------------

_DEFAULT_AGENTS = ["coder", "architect", "reviewer", "tester", "debugger", "refactor", "security"]

_DEFAULT_MODELS = [
    "anthropic/claude-sonnet-4-5",
    "anthropic/claude-haiku-4-5",
    "openai/gpt-4o",
    "openai/gpt-4o-mini",
    "ollama/llama3.1",
]


class SetupWizard:
    """Interactive wizard that guides the user through initial project setup.

    Usage::

        wizard = SetupWizard(project_dir=Path.cwd())
        result = await wizard.run()
    """

    def __init__(self, project_dir: Path | None = None) -> None:
        self._project_dir = project_dir or Path.cwd()

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    async def run(self) -> WizardResult:
        """Run all wizard steps and return a WizardResult.

        Falls back to defaults when prompt_toolkit is unavailable or when
        running non-interactively.
        """
        try:
            return await self._run_interactive()
        except (ImportError, EOFError, KeyboardInterrupt):
            return self._default_result()

    def generate_config(self, result: WizardResult, output_path: Path | None = None) -> Path:
        """Write a ``.lidco/config.yaml`` based on *result*.

        Returns the path of the written file.
        """
        dest = output_path or (self._project_dir / ".lidco" / "config.yaml")
        dest.parent.mkdir(parents=True, exist_ok=True)

        lines = [
            "# LIDCO configuration — generated by setup wizard",
            "llm:",
            f"  default_model: {result.model}",
            "",
            "agents:",
            f"  default_agent: {result.agent}",
            "",
            "project:",
            f"  type: {result.project_type}",
        ]
        dest.write_text("\n".join(lines) + "\n", encoding="utf-8")
        return dest

    # ------------------------------------------------------------------
    # Internal: interactive flow
    # ------------------------------------------------------------------

    async def _run_interactive(self) -> WizardResult:
        from prompt_toolkit import prompt as pt_prompt

        # Step 1: Detect project type
        detected = detect_project_type(self._project_dir)
        project_type_raw = pt_prompt(
            f"[1/5] Project type (detected: {detected}): ",
            default=detected,
        ).strip() or detected

        # Step 2: Primary agent
        agent_raw = pt_prompt(
            f"[2/5] Primary agent {_DEFAULT_AGENTS}: ",
            default="coder",
        ).strip() or "coder"

        # Step 3: LLM API key (just ask if they've set it)
        api_key_raw = pt_prompt(
            "[3/5] Paste your LLM API key (or press Enter to skip): ",
            is_password=True,
        ).strip()

        api_key_set = bool(api_key_raw)
        if api_key_set:
            # Store in environment for this session; advise user to persist
            os.environ.setdefault("ANTHROPIC_API_KEY", api_key_raw)

        # Step 4: Model preference
        model_raw = pt_prompt(
            f"[4/5] Model preference {_DEFAULT_MODELS}: ",
            default=_DEFAULT_MODELS[0],
        ).strip() or _DEFAULT_MODELS[0]

        # Step 5: Generate config
        result = WizardResult(
            project_type=project_type_raw,
            agent=agent_raw,
            model=model_raw,
            api_key_set=api_key_set,
        )
        config_path = self.generate_config(result)
        print(f"\n[5/5] Config written to {config_path}")

        return result

    def _default_result(self) -> WizardResult:
        return WizardResult(
            project_type=detect_project_type(self._project_dir),
            agent="coder",
            model=_DEFAULT_MODELS[0],
            api_key_set=False,
        )
